In [1]:
import seaborn
import pandas as pd
import numpy as np


In [3]:
titanic = seaborn.load_dataset('titanic')
titanic.sample()

survived  pclass     sex   age  sibsp  parch    fare embarked  class  \
786         1       3  female  18.0      0      0  7.4958        S  Third   

       who  adult_male deck  embark_town alive  alone  
786  woman       False  NaN  Southampton   yes   True

# Task 1

In [4]:
# Split the target 'survived' off from the predictors
X = titanic.drop('survived', axis=1)
y = titanic['survived']

In [5]:
# convert the 'sex' column to a binary where 1 represents female
X['sex'] = X['sex'].map({'male':0, 'female':1})

# Task 2

In [8]:
# Implement a train-test split using all default arguments and random_state=42
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Task 3

We will fit a logistic regression model using only `sex` and `fare`.  Remember that logistic regression uses regularization by default.  That means that scaling will have an effect on the scores. 

In [20]:
# Fit a standard scaler to train columns of interest, and transform both train and test
from sklearn.preprocessing import StandardScaler

cols_of_interest = ['sex', 'fare']

ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train[cols_of_interest])
X_test_sc = ss.transform(X_test[cols_of_interest])

In [22]:
# Instantiate a logistic regression model with the default arguments and random_state=42
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(random_state=42)

# Fit on the scaled training data. 
lr.fit(X_train_sc, y_train)

LogisticRegression(random_state=42)

# Task 4

The `predict()` method applies a decision threshold to the predicted probabilities.

In [25]:
# Model test predictions
y_hat = lr.predict(X_test_sc)

Under the hood, the model is applying a decision threshold to assign a 0 or 1 prediction. 
For the exercise below, apply a decision threshold of .5 to the predicted probabities, so that you can recreate the 0 or 1 predictions stored in y_hat above.

In [41]:
y_hat

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0])

In [44]:
y_hat_proba

array([[0.8299281 , 0.1700719 ],
       [0.83692757, 0.16307243],
       [0.84062732, 0.15937268],
       [0.2676156 , 0.7323844 ],
       [0.31527618, 0.68472382],
       [0.18333385, 0.81666615],
       [0.3233396 , 0.6766604 ],
       [0.82575758, 0.17424242],
       [0.3233396 , 0.6766604 ],
       [0.28183303, 0.71816697],
       [0.76547017, 0.23452983],
       [0.8404493 , 0.1595507 ],
       [0.28359252, 0.71640748],
       [0.84162125, 0.15837875],
       [0.83326972, 0.16673028],
       [0.25449977, 0.74550023],
       [0.76650968, 0.23349032],
       [0.32315551, 0.67684449],
       [0.83326972, 0.16673028],
       [0.76756191, 0.23243809],
       [0.84066888, 0.15933112],
       [0.81229741, 0.18770259],
       [0.32309741, 0.67690259],
       [0.83876806, 0.16123194],
       [0.83104367, 0.16895633],
       [0.81010056, 0.18989944],
       [0.8103933 , 0.1896067 ],
       [0.83326972, 0.16673028],
       [0.81010056, 0.18989944],
       [0.32309741, 0.67690259],
       [0.

In [48]:
# Convert these predicted probabilities to 0/1 predictions
y_hat_proba = lr.predict_proba(X_test_sc)

# Apply threshold here
y_hat_by_hand = np.array([int(round(y[1])) for y in y_hat_proba])

In [49]:
y_hat_by_hand

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0])

In [50]:
assert (y_hat == y_hat_by_hand).sum() == len(y_hat)

# Stretch Task

For the final task, we will recreate the predicted probabilities using the coefficients and intercept of the fitted model.  The parameters that the fit method calculates are fed into a linear equation, whose output represents log odds. That can be confusing, but its easier to think about if you think about what results after feeding the log odds into the sigmoid function.

In [51]:
def sigmoid(log_odd):
    
    '''
    The link function translates a log_odd prediction
    and returns a probability of class 1 with a
    number between 0 and 1.
    '''
    
    return 1/(1+np.e**(-log_odd))
    

The sigmoid takes a log odd input, and translates it to a number between 0 and 1.  The sigmoid ensures that any result of the linear equation (log odds) which is negative translates into a probability closer to 0 than 1; in other words, below .5.  A positive log odd results in a prediction closer to 1 than 0; in other words above .5.

In the cell below, use the coef_ and intercept_ attributes from the fit model to calculate the log_odds for each record in the test set. Then pass these log_odds into the sigmoid function above.

In [69]:
lr.coef_

array([[1.14069272, 0.5478949 ]])

In [53]:
lr.intercept_

array([-0.58133268])

In [71]:
# Log odds are the output of the dot product of X_test, 
# a version of the coef_ attribute, plus the interceps_ attribute. 
log_odds = np.add(lr.intercept_, (np.dot(lr.coef_, X_test_sc)))

# use a list comprehension to apply the sigmoid function to each log_odd.
predict_proba_by_hand = None

ValueError: shapes (1,2) and (223,2) not aligned: 2 (dim 1) != 223 (dim 0)

In [68]:
assert np.isclose(predict_proba_by_hand, y_hat_proba[:,1]).sum() == 223

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''